# Generated by Django 5.1.3 on 2024-11-25 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_original', models.ImageField(upload_to='images/originals/')),
                ('img_processed', models.ImageField(blank=True, null=True, upload_to='images/processed/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pixion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pixion.image')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pixion.usuario')),
            ],
        ),
    ]
