# Generated by Django 5.1.3 on 2024-11-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-date']},
        ),
    ]
