# Generated by Django 5.1.3 on 2024-11-26 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixion', '0002_alter_comment_options_alter_image_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='pixion.image')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_images', to='pixion.usuario')),
            ],
            options={
                'unique_together': {('id_image', 'id_user')},
            },
        ),
    ]
